### ISSUE TITLE
Support arbitrary mpv options

### ISSUE THREAD

**Issue by yuvadm** [yuvadm/streamlib#2]
Currently the only *special* mpv option supported is `http_headers` which is converted to `mpv`'s `--http-header-fields` argument.

It might be nice to support arbitrary arguments using TOML nested tables with the following library specification:

```toml
[foo]
url = "http://example.com/foo.pls"

  [foo.mpv]
  http-header-fields = ["User-Agent: foo"]
  cookies-file = "path/to/cookies"
  hls-bitrate = "no"
```

Those parameters can then be immediately translated to `--key-name` args that are passed on to the `mpv` invocation.
